# Language: German (Switzerland) (ch+de)
# Maintained by Patrick Jörg <patrickjoerg@gmx.ch>. No Copyright, enjoy!

---
outlines:
    default:       { width: 48.872,  height: 42 }
    change-view:   { width: 73.308,  height: 42 }
    change-view-2: { width: 85.526,  height: 42 }
    placeholder:   { width: 48.872,  height: 42 }
    spaceline:     { width: 134.398, height: 42 }
    special:       { width: 48.872,  height: 42 }
    special-2:     { width: 73.308,  height: 42 }
    special-3:     { width: 85.526,  height: 42 }

views:
    base:
        - "q w e r t z u i o p ü"
        - "a s d f g h j k l ö ä"
        - "show_upper y x c v b n m -- BackSpace"
        - "show_numbers preferences ? ' space , . Return"
    upper:
        - "Q W E R T Z U I O P Ü"
        - "A S D F G H J K L Ö Ä"
        - "show_upper Y X C V B N M -- BackSpace"
        - "show_numbers preferences ! \" space - _ Return"
    numbers:      
        - "1 2 3 4 5 6 7 8 9 0 ²"
        - "@ * + - = ( ) ~ < > ³"
        - "show_symbols # & / \\ √ ; : -- BackSpace"
        - "show_letters preferences ? _ space , . Return"
    symbols:
        - "€ $ £ ¥ % | § µ [ ] ²"
        - "© ® § ` ^ { } · ¡ ¿ ³"
        - "show_numbers « » ÷ × “ ” „ -- BackSpace"
        - "show_letters preferences ! - space , . Return"

buttons:
    show_upper:
        action:
            locking:
                lock_view: "upper"
                unlock_view: "base"
        outline: "change-view"
        icon: "key-shift"
    BackSpace:
        outline: "special-2"
        icon: "edit-clear-symbolic"
        action: "erase"
    preferences:
        action: "show_prefs"
        outline: "special"
        icon: "keyboard-mode-symbolic"
    show_numbers:
        action:
            set_view: "numbers"
        outline: "change-view"
        label: "123"
    show_letters:
        action:
            set_view: "base"
        outline: "change-view"
        label: "ABC"
    show_symbols:
        action:
            set_view: "symbols"
        outline: "change-view"
        label: "*/="
    space:
        outline: "spaceline"
        text: " "
    Return:
        outline: "special-3"
        icon: "key-enter"
        keysym: "Return"
    --:
        outline: "placeholder"
        text: ""
