# Language: German (Neo 2)
---
outlines:
    default:            { width: 32.415, height: 52 }
    change-view:        { width: 48.622, height: 52 }
    fill:               { width: 64.83,  height: 52 }
    spaceline:          { width: 112.45, height: 52 }
    special:            { width: 32.415, height: 52 }
    special-2:          { width: 48.622, height: 52 }
    subtle-highlight:   { width: 32.415, height: 52 }
    subtle-highlight-2: { width: 64.83,  height: 52 }

views:
    base:
        - "x v l c w k h g f q ß"
        - "u i a e o s n r t d y"
        - "show_upper ü ö ä p z b m j BackSpace"
        - "show_numbers show_eschars preferences space , . Return"
    upper:
        - "X V L C W K H G F Q ẞ"
        - "U I A E O S N R T D Y"
        - "show_upper Ü Ö Ä P Z B M J BackSpace"
        - "show_numbers show_eschars preferences space ! ? Return"
    numbers:
        - "1 2 3 4 5 6 7 8 9 0 ²"
        - "@ # € % & - _ + ( ) ³"
        - "show_symbols ; \" ' : = < > BackSpace"
        - "show_letters show_eschars preferences space , . Return"
    symbols:
        - "~ ` ´ | · √ µ ÷ × ¶ ²"
        - "© ® £ $ ¥ ^ ° * { } ³"
        - "show_numbers \\ / § π τ [ ] BackSpace"
        - "show_letters show_eschars preferences space , . Return"
    eschars:
        - "ä-subtle-highlight è é ö-subtle-highlight ü-subtle-highlight-2 Ä-subtle-highlight È É Ö-subtle-highlight Ü-subtle-highlight"
        - "à â ê î ô À Â Ê Î Ô"
        - "show_numbers « » ç Ç æ œ ß-subtle-highlight BackSpace"
        - "show_letters show_eschars preferences space „ “ Return"

buttons:
    show_upper:
        action:
            locking:
                lock_view: "upper"
                unlock_view: "base"
        outline: "change-view"
        icon: "key-shift"
    BackSpace:
        outline: "special-2"
        icon: "edit-clear-symbolic"
        action: "erase"
    preferences:
        action: "show_prefs"
        outline: "special"
        icon: "keyboard-mode-symbolic"
    show_numbers:
        action:
            set_view: "numbers"
        outline: "change-view"
        label: "123"
    show_letters:
        action:
            set_view: "base"
        outline: "change-view"
        label: "ABC"
    show_symbols:
        action:
            set_view: "symbols"
        outline: "change-view"
        label: "*/="
    show_eschars:
        action:
            locking:
                lock_view: "eschars"
                unlock_view: "base"
        outline: "change-view"
        label: "Ää"
    space:
        outline: "spaceline"
        text: " "
    Return:
        outline: "special-2"
        icon: "key-enter"
        keysym: "Return"
    ä-subtle-highlight:
        outline: "subtle-highlight"
        text: "ä"
    ö-subtle-highlight:
        outline: "subtle-highlight"
        text: "ö"
    ü-subtle-highlight-2:
        outline: "subtle-highlight-2"
        text: "ü"
    Ä-subtle-highlight:
        outline: "subtle-highlight"
        text: "Ä"
    Ö-subtle-highlight:
        outline: "subtle-highlight"
        text: "Ö"
    Ü-subtle-highlight:
        outline: "subtle-highlight"
        text: "Ü"
    ß-subtle-highlight:
        outline: "subtle-highlight"
        text: "ß"
    ô:
        outline: "fill"
    Ç:
        outline: "fill"
    ":":
        outline: "fill"
    π:
        outline: "fill"