# Language: German
---
outlines:
    default:            { width: 48.872,  height: 42 }
    change-view:        { width: 73.308,  height: 42 }
    fill:               { width: 97.744,  height: 42 }
    placeholder:        { width: 48.872,  height: 42 }
    spaceline:          { width: 171.052, height: 42 }
    special:            { width: 48.872,  height: 42 }
    special-2:          { width: 73.308,  height: 42 }
    subtle-highlight:   { width: 48.872,  height: 42 }
    subtle-highlight-2: { width: 97.744,  height: 42 }

views:
    base:
        - "q w e r t z u i o p ü"
        - "a s d f g h j k l ö ä"
        - "show_upper y x c v b n m ß BackSpace"
        - "show_numbers show_eschars preferences space , . Return"
    upper:
        - "Q W E R T Z U I O P Ü"
        - "A S D F G H J K L Ö Ä"
        - "show_upper Y X C V B N M - BackSpace"
        - "show_numbers show_eschars preferences space ! ? Return"
    numbers:
        - "1 2 3 4 5 6 7 8 9 0 ²"
        - "@ # € % & - _ + ( ) ³"
        - "show_symbols ; \" ' : = < > -- BackSpace"
        - "show_letters show_eschars preferences space , . Return"
    symbols:
        - "~ ` ´ | · √ µ ÷ × ¶ ²"
        - "© ® £ $ ¥ ^ ° * { } ³"
        - "show_numbers \\ / § π τ [ ] -- BackSpace"
        - "show_letters show_eschars preferences space , . Return"
    eschars:
        - "ä-subtle-highlight è é ö-subtle-highlight ü-subtle-highlight-2 Ä-subtle-highlight È É Ö-subtle-highlight Ü-subtle-highlight"
        - "à â ê î ô À Â Ê Î Ô"
        - "show_numbers « » ç Ç æ œ ß-subtle-highlight ẞ-subtle-highlight BackSpace"
        - "show_letters show_eschars preferences space „ “ Return"

buttons:
    show_upper:
        action:
            locking:
                lock_view: "upper"
                unlock_view: "base"
        outline: "change-view"
        icon: "key-shift"
    BackSpace:
        outline: "special-2"
        icon: "edit-clear-symbolic"
        action: "erase"
    preferences:
        action: "show_prefs"
        outline: "special"
        icon: "keyboard-mode-symbolic"
    show_numbers:
        action:
            set_view: "numbers"
        outline: "change-view"
        label: "123"
    show_letters:
        action:
            set_view: "base"
        outline: "change-view"
        label: "ABC"
    show_symbols:
        action:
            set_view: "symbols"
        outline: "change-view"
        label: "*/="
    show_eschars:
        action:
            locking:
                lock_view: "eschars"
                unlock_view: "base"
        outline: "change-view"
        label: "Ää"
    space:
        outline: "spaceline"
        text: " "
    Return:
        outline: "special-2"
        icon: "key-enter"
        keysym: "Return"
    ä-subtle-highlight:
        outline: "subtle-highlight"
        text: "ä"
    ö-subtle-highlight:
        outline: "subtle-highlight"
        text: "ö"
    ü-subtle-highlight-2:
        outline: "subtle-highlight-2"
        text: "ü"
    Ä-subtle-highlight:
        outline: "subtle-highlight"
        text: "Ä"
    Ö-subtle-highlight:
        outline: "subtle-highlight"
        text: "Ö"
    Ü-subtle-highlight:
        outline: "subtle-highlight"
        text: "Ü"
    ß-subtle-highlight:
        outline: "subtle-highlight"
        text: "ß"
    ẞ-subtle-highlight:
        outline: "subtle-highlight"
        text: "ẞ"
    --:
        outline: "placeholder"
        text: ""
    ô:
        outline: "fill"