# Language: Slovenian
---
outlines:
    default:          { width: 35.657, height: 52 }
    change-view:      { width: 53.485, height: 52 }
    spaceline:        { width: 89.144, height: 52 }
    special:          { width: 35.657, height: 52 }
    special-2:        { width: 53.485, height: 52 }
    subtle-highlight: { width: 35.657, height: 52 }

views:
    base:
        - "q w e r t z u i o p"
        - "a s d f g h j k l č"
        - "show_upper y x c v b n m BackSpace"
        - "show_numbers show_accents preferences space , . Return"
    upper:
        - "Q W E R T Z U I O P"
        - "A S D F G H J K L Č"
        - "show_upper Y X C V B N M BackSpace"
        - "show_numbers show_upper_accents preferences space ! ? Return"
    numbers:
        - "1 2 3 4 5 6 7 8 9 0"
        - "@ # $ % & - _ + ( )"
        - "show_symbols , \" ' : ; ! ? BackSpace"
        - "show_letters show_accents preferences space , . Return"
    symbols:
        - "~ ` | · √ π τ ÷ × ¶"
        - "© ® £ € ¥ ^ ° * { }"
        - "show_numbers \\ / < > = [ ] BackSpace"
        - "show_letters show_accents preferences space § ¤ Return"
    accents:
        - "á é ẹ́  í ó ọ́  ú ŕ š đ"
        - "ȃ ȇ ẹ̑  ȋ ȏ ọ̑  ȗ ȓ ć ž"
        - "accents_show_upper à è ì ò ù ö ü BackSpace"
        - "show_letters show_accents preferences space ĺ ł Return"
    upper_accents:
        - "Á É Ẹ́  Í Ó Ọ́  Ú Ŕ Š Đ"
        - "Ȃ Ȇ Ẹ̑  Ȋ Ȏ Ọ̑  Ȗ Ȓ Ć Ž"
        - "accents_show_upper À È Ì Ò Ù Ö Ü BackSpace"
        - "show_letters show_upper_accents preferences space Ĺ Ł Return"

buttons:
    show_upper:
        action:
            locking:
                lock_view: "upper"
                unlock_view: "base"
        outline: "change-view"
        icon: "key-shift"
    accents_show_upper:
        action:
            locking:
                lock_view: "upper_accents"
                unlock_view: "base"
        outline: "change-view"
        icon: "key-shift"
    BackSpace:
        outline: "special-2"
        icon: "edit-clear-symbolic"
        action: "erase"
    preferences:
        action: "show_prefs"
        outline: "special"
        icon: "keyboard-mode-symbolic"
    show_numbers:
        action:
            set_view: "numbers"
        outline: "change-view"
        label: "123"
    show_letters:
        action:
            set_view: "base"
        outline: "change-view"
        label: "ABC"
    show_symbols:
        action:
            set_view: "symbols"
        outline: "change-view"
        label: "*/="
    show_accents:
        action:
            locking:
                lock_view: "accents"
                unlock_view: "base"
        outline: "change-view"
        label: "Ćž"
    show_upper_accents:
        action:
            locking:
                lock_view: "upper_accents"
                unlock_view: "base"
        outline: "change-view"
        label: "Ćž"
    space:
        outline: "spaceline"
        text: " "
    Return:
        outline: "special-2"
        icon: "key-enter"
        keysym: "Return"
    š:
        outline: "subtle-highlight"
    Š:
        outline: "subtle-highlight"
    ž:
        outline: "subtle-highlight"
    Ž:
        outline: "subtle-highlight"
    ć:
        outline: "subtle-highlight"
    Ć:
        outline: "subtle-highlight"
    đ:
        outline: "subtle-highlight"
    Đ:
        outline: "subtle-highlight"